### ISSUE TITLE
有没有前台展示系统

### ISSUE THREAD

**Issue by Andy5972** [zaiyunduan123/jesper_shop#1]

**Comment by zaiyunduan123** [comment]
这只是后台管理系统

**Comment by exphastur** [comment]
没有建表语句的话，注册登录功能做不了吧
________________________________


发件人： Jesper<mailto:notifications@github.com>
发送时间： 2018-06-19 14:46
收件人： zaiyunduan123/jesper_shop<mailto:jesper_shop@noreply.github.com>
抄送： Subscribed<mailto:subscribed@noreply.github.com>
主题： Re: [zaiyunduan123/jesper_shop] 有没有前台展示系统 (#1)

这只是后台管理系统

**Comment by zaiyunduan123** [comment]
数据库文件已上传

**Comment by exphastur** [comment]
谢谢 大佬

________________________________
郭瑞轩  中科软紫金项目组  承保组 开发工程师
--------------------------------------------------------
中科软科技股份有限公司
应用集成事业群  应用产品事业十部
邮箱：exphastur@hotmail.com.cn<mailto:wu.chao@sinosoft.com.cn>
手机：15850548782
公司地址：北京市海淀区中关村新科祥园甲6号楼（100190）
网址：http://www.sinosoft.com.cn/

声明(statement):

此电子邮件包含来自中科软科技股份有限公司的信息，而且是机密的或者专用的信息。这些信息是供以上列出的收件人使用的。如果您不是此邮件的预期收件人，请勿阅读、复制、泄露、转发或存储此邮件。如果已误收此邮件，请通知发件人。本邮件可作为双方沟通交流使用，如涉及本公司正式承诺，则该表达均须加盖本公司公章后方可生效。

This e-mail may contain confidential and/or privileged information from Sinosoft Co., LTD and is intended solely for the attention and use of the person(s) named above. If you are not the intended recipient (or have received this e-mail in error), please notify the sender immediately and destroy this e-mail. Any unauthorized reading, copying, disclosure, forwarding and storage of the material in this email is strictly forbidden.The content of this message can be used to communicate between both sides,such as the two sides reach an agreement or subject to a formal commitment of SINOSOFT, the expression of the SINOSOFT only takes effect after affixing the Official Seal of the SINOSOFT.


声明(statement):



此电子邮件包含来自中科软科技股份有限公司的信息，而且是商业保密的或者专用的信息。这些信息是供以上列出的收件人使用的。如果您不是此邮件的预期收件人，请勿阅读、复制、泄露、转发或存储此邮件。如果已误收此邮件，请通知发件人。本邮件可作为双方沟通交流使用，如涉及本公司正式承诺，则该表达均须加盖本公司公章后方可生效。



This e-mail may contain confidential and/or privileged information from Sinosoft Co., LTD and is intended solely for the attention and use of the person(s) named above. If you are not the intended recipient (or have received this e-mail in error), please notify the sender immediately and destroy this e-mail. Any unauthorized reading, copying, disclosure, forwarding and storage of the material in this email is strictly forbidden.The content of this message can be used to communicate between both sides,such as the two sides reach an agreement or subject to a formal commitment of SINOSOFT, the expression of the SINOSOFT only takes effect after affixing the Official Seal of the SINOSOFT.


发件人： Jesper<mailto:notifications@github.com>
发送时间： 2018-06-19 14:52
收件人： zaiyunduan123/jesper_shop<mailto:jesper_shop@noreply.github.com>
抄送： exphastur<mailto:exphastur@hotmail.com>; Comment<mailto:comment@noreply.github.com>
主题： Re: [zaiyunduan123/jesper_shop] 有没有前台展示系统 (#1)

数据库文件已上传
