### ISSUE TITLE
redis的密码。。。。

### ISSUE THREAD

**Issue by xinyuow** [zaiyunduan123/jesper_shop#12]
我说我怎么配置了redis的密码还一直提示我 NOAUTH Authentication required
原来是new JedisPool的时候密码一项直接传的null.....

**Comment by zaiyunduan123** [comment]
这个确实有问题，我当时redis没有设置密码，所以导致如果redis设置密码这里就有问题

**Comment by zaiyunduan123** [comment]
已修复，谢谢
