### ISSUE TITLE
template stats文件缺失

### ISSUE THREAD

**Issue by JNUpython** [zaiyunduan123/jesper_shop#9]

**Comment by JNUpython** [comment]
hello！ dashboard无法正常显示，错误提示
org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "class path resource [templates/dashboard.html]")
	at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:241) ~[thymeleaf-3.0.9.RELEASE.jar:3.0.9.RELEASE]

<h1 class="no-margins" th:text="${stats.mOrderNum}">--月订单数</h1>
stats.html文件没有找到，能否帮忙解答下了

**Comment by zaiyunduan123** [comment]
我刚刚启动了一下，没问题。
启动项目前本地要开启Redis，MongoDB可以不开，启动项目后访问http://localhost:8080/user/login

**Comment by JNUpython** [comment]
Thx, 已经可以正常运行起来，我看idea提示template dashboard提示stats 部分红色以为缺少stats这个html文件
